spring.application.name=graalvm-sck-app
spring.main.cloud-platform=kubernetes

# Import Kubernetes config (no optional, since it runs in K8s)
spring.config.import=kubernetes:

# ConfigMap settings
spring.cloud.kubernetes.config.enabled=true
spring.cloud.kubernetes.config.namespace=graalvm

# Secret settings
spring.cloud.kubernetes.secrets.enabled=true
spring.cloud.kubernetes.secrets.namespace=graalvm

# Logging for debugging
logging.level.org.springframework.cloud.kubernetes=DEBUG
logging.level.io.fabric8=DEBUG